## Copyright (c) 2011 The WebM project authors. All Rights Reserved.
## 
## Use of this source code is governed by a BSD-style license
## that can be found in the LICENSE file in the root of the source
## tree. An additional intellectual property rights grant can be found
## in the file PATENTS.  All contributing project authors may
## be found in the AUTHORS file in the root of the source tree.
# This file automatically generated by configure. Do not edit!
TOOLCHAIN := armv7-android-gcc
ALL_TARGETS += libs

PREFIX=android/armeabi-v7a
ifeq ($(MAKECMDGOALS),dist)
DIST_DIR?=vpx-vp8-vp9-nopost-nodocs-armv7-android-v1.6.1
else
DIST_DIR?=$(DESTDIR)android/armeabi-v7a
endif
LIBSUBDIR=lib

VERSION_STRING=v1.6.1

VERSION_MAJOR=1
VERSION_MINOR=6
VERSION_PATCH=1

CONFIGURE_ARGS=--prefix=android/armeabi-v7a --target=armv7-android-gcc --sdk-path=/home/ring0/develop/android-ndk-r15c --enable-runtime-cpu-detect --disable-install-docs --disable-examples --disable-tools --disable-docs --enable-vp8 --enable-vp9
CONFIGURE_ARGS?=--prefix=android/armeabi-v7a --target=armv7-android-gcc --sdk-path=/home/ring0/develop/android-ndk-r15c --enable-runtime-cpu-detect --disable-install-docs --disable-examples --disable-tools --disable-docs --enable-vp8 --enable-vp9
