## Copyright (c) 2011 The WebM project authors. All Rights Reserved.
## 
## Use of this source code is governed by a BSD-style license
## that can be found in the LICENSE file in the root of the source
## tree. An additional intellectual property rights grant can be found
## in the file PATENTS.  All contributing project authors may
## be found in the AUTHORS file in the root of the source tree.
# This file automatically generated by configure. Do not edit!
SRC_PATH="/home/ring0/git/FFmpegAndroid/jni/libvpx"
SRC_PATH_BARE=/home/ring0/git/FFmpegAndroid/jni/libvpx
BUILD_PFX=
TOOLCHAIN=armv7-android-gcc
ASM_CONVERSION=/home/ring0/git/FFmpegAndroid/jni/libvpx/build/make/ads2gas.pl
GEN_VCPROJ=
MSVS_ARCH_DIR=

CC=/home/ring0/develop/android-ndk-r15c/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc
CXX=/home/ring0/develop/android-ndk-r15c/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-g++
AR=/home/ring0/develop/android-ndk-r15c/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-ar
LD=/home/ring0/develop/android-ndk-r15c/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-g++
AS=/home/ring0/develop/android-ndk-r15c/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-as
STRIP=/home/ring0/develop/android-ndk-r15c/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-strip
NM=/home/ring0/develop/android-ndk-r15c/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-nm

CFLAGS  = -fpic -ffunction-sections -funwind-tables -fstack-protector -no-canonical-prefixes -march=armv5te -mtune=xscale -msoft-float -fno-exceptions -mfloat-abi=softfp -mfpu=neon -I/home/ring0/develop/android-ndk-r15c/platforms/android-19/arch-arm/usr/include --sysroot=/home/ring0/develop/android-ndk-r15c/platforms/android-26/arch-arm -I/home/ring0/develop/android-ndk-r15c/sources/android/cpufeatures -DNDEBUG -O3 -fPIC -Wall -Wdeclaration-after-statement -Wdisabled-optimization -Wfloat-conversion -Wpointer-arith -Wtype-limits -Wcast-qual -Wvla -Wimplicit-function-declaration -Wuninitialized -Wunused -Wextra -Wundef
CXXFLAGS  =  --sysroot=/home/ring0/develop/android-ndk-r15c/platforms/android-26/arch-arm -I/home/ring0/develop/android-ndk-r15c/sources/android/cpufeatures -DNDEBUG -O3 -fPIC -Wall -Wdisabled-optimization -Wfloat-conversion -Wpointer-arith -Wtype-limits -Wcast-qual -Wvla -Wuninitialized -Wunused -Wextra
ARFLAGS = -crs$(if $(quiet),,v)
LDFLAGS = -Wl,-Bsymbolic --sysroot=/home/ring0/develop/android-ndk-r15c/platforms/android-19/arch-arm -no-canonical-prefixes -Wl,--no-undefined -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now -L/home/ring0/develop/android-ndk-r15c/platforms/android-19/arch-arm/usr/lib -lm -lgcc --sysroot=/home/ring0/develop/android-ndk-r15c/platforms/android-26/arch-arm -Wl,--fix-cortex-a8
ASFLAGS =  --defsym ARCHITECTURE=7 -march=armv7-a -mfloat-abi=softfp -mfpu=neon
extralibs = 
AS_SFX    = .S
EXE_SFX   = 
VCPROJ_SFX = 
RTCD_OPTIONS = 
fmt_deps = sed -e 's;^\([a-zA-Z0-9_]*\)\.o;${@:.d=.o} $@;'
ARCH_ARM=yes
HAVE_NEON=yes
HAVE_NEON_ASM=yes
HAVE_VPX_PORTS=yes
HAVE_PTHREAD_H=yes
HAVE_UNISTD_H=yes
CONFIG_DEPENDENCY_TRACKING=yes
CONFIG_INSTALL_BINS=yes
CONFIG_INSTALL_LIBS=yes
CONFIG_GCC=yes
CONFIG_PIC=yes
CONFIG_RUNTIME_CPU_DETECT=yes
CONFIG_MULTITHREAD=yes
CONFIG_VP8_ENCODER=yes
CONFIG_VP8_DECODER=yes
CONFIG_VP9_ENCODER=yes
CONFIG_VP9_DECODER=yes
CONFIG_VP8=yes
CONFIG_VP9=yes
CONFIG_ENCODERS=yes
CONFIG_DECODERS=yes
CONFIG_SPATIAL_RESAMPLING=yes
CONFIG_REALTIME_ONLY=yes
CONFIG_STATIC=yes
CONFIG_OS_SUPPORT=yes
CONFIG_WEBM_IO=yes
CONFIG_LIBYUV=yes
CONFIG_TEMPORAL_DENOISING=yes
HAVE_GNU_STRIP=yes
