/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ring0_ffmpeg_FFmpegHelper */

#ifndef _Included_com_ring0_ffmpeg_FFmpegHelper
#define _Included_com_ring0_ffmpeg_FFmpegHelper
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT void JNICALL Java_com_ring0_ffmpeg_FFmpegHelper_decoderVideoToYuv
  (JNIEnv *, jclass, jstring, jstring, jint, jint);

JNIEXPORT void JNICALL Java_com_ring0_ffmpeg_FFmpegHelper_decoderAudioToPcm
  (JNIEnv *, jclass, jstring, jstring, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
