/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ring0_opensl_OpenSLHelper */

#ifndef _Included_com_ring0_opensl_OpenSLHelper
#define _Included_com_ring0_opensl_OpenSLHelper
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT void JNICALL Java_com_ring0_opensl_OpenSLHelper_opensl_1play
  (JNIEnv *, jclass, jbyteArray, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
