/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ring0_opengl_OpenGLHelper */

#ifndef _Included_com_ring0_opengl_OpenGLHelper
#define _Included_com_ring0_opengl_OpenGLHelper
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT void JNICALL Java_com_ring0_opengl_OpenGLHelper_opengl_1init
  (JNIEnv *, jclass);

JNIEXPORT void JNICALL Java_com_ring0_opengl_OpenGLHelper_opengl_1change
  (JNIEnv *, jclass, jint, jint);

JNIEXPORT void JNICALL Java_com_ring0_opengl_OpenGLHelper_opengl_1draw
  (JNIEnv *, jclass, jstring, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
